INSERT ALL
INTO reply VALUES ('R1', 'Key concepts in machine learning include algorithms, models, and datasets.', 'INS_24_3', TO_DATE('15-09-2022', 'DD-MM-YYYY'), 'Q1_ML_20_A_STU_22_1')
INTO reply VALUES ('R2', 'Overfitting in machine learning models can be addressed using techniques like regularization and cross-validation.', 'INS_24_1', TO_DATE('17-09-2022', 'DD-MM-YYYY'), 'Q2_ML_20_A_STU_22_1')
INTO reply VALUES ('R3', 'Artificial Intelligence basics cover machine learning algorithms, neural networks, and expert systems.', 'INS_24_2', TO_DATE('16-09-2022', 'DD-MM-YYYY'), 'Q1_AI_21_B_STU_22_2')
INTO reply VALUES ('R4', 'Real-world applications of AI include chatbots, recommendation systems, and autonomous vehicles.', 'INS_24_4', TO_DATE('19-09-2022', 'DD-MM-YYYY'), 'Q2_AI_21_B_STU_22_2')
INTO reply VALUES ('R5', 'Data preprocessing involves cleaning, transforming, and analyzing data to prepare it for analysis.', 'INS_24_5', TO_DATE('18-09-2022', 'DD-MM-YYYY'), 'Q1_DS_23_A_STU_22_4')
INTO reply VALUES ('R6', 'Popular data visualization libraries include Matplotlib, Seaborn, and Plotly.', 'INS_23_1', TO_DATE('21-09-2022', 'DD-MM-YYYY'), 'Q2_DS_23_A_STU_22_4')
INTO reply VALUES ('R7', 'Web development fundamentals include HTML, CSS, and JavaScript.', 'INS_23_2', TO_DATE('17-09-2022', 'DD-MM-YYYY'), 'Q1_WD_20_B_STU_23_1')
INTO reply VALUES ('R8', 'Responsive web design ensures that web pages render well on various devices and window or screen sizes.', 'INS_20_2', TO_DATE('20-09-2022', 'DD-MM-YYYY'), 'Q2_WD_20_B_STU_23_1')
INTO reply VALUES ('R9', 'Advantages of using React.js include component reusability, improved performance, and faster development.', 'INS_23_3', TO_DATE('19-09-2022', 'DD-MM-YYYY'), 'Q1_WD_23_A_STU_23_2')
INTO reply VALUES ('R10', 'State management in React can be achieved using hooks like useState and useReducer.', 'INS_24_6', TO_DATE('22-09-2022', 'DD-MM-YYYY'), 'Q2_WD_23_A_STU_23_2')
INTO reply VALUES ('R11', 'The basics of React.js include JSX syntax, components, and props.', 'INS_24_5', TO_DATE('15-09-2022', 'DD-MM-YYYY'), 'Q1_REACT_24_B_STU_23_3')
INTO reply VALUES ('R12', 'Events in React are handled using event handlers like onClick and onChange.', 'IN_23_8', TO_DATE('19-09-2022', 'DD-MM-YYYY'), 'Q2_REACT_24_B_STU_23_3')
INTO reply VALUES ('R13', 'Differences between React class components and functional components include syntax and lifecycle methods.', 'IN_23_5', TO_DATE('18-09-2022', 'DD-MM-YYYY'), 'Q1_REACT_23_A_STU_23_4')
INTO reply VALUES ('R14', 'Hooks in React provide a way to use state and other React features without writing a class.', 'IN_24_16', TO_DATE('21-09-2022', 'DD-MM-YYYY'), 'Q3_REACT_23_A_STU_24')
INTO reply  VALUES ('R15', 'Hooks and custom hooks in React allow for the reuse of stateful logic across multiple components.', 'IN_23_10', TO_DATE('21-09-2022', 'DD-MM-YYYY'), 'Q3_REACT_23_A_STU_24')
INTO reply VALUES ('R16', 'Machine learning concepts like regression, classification, and clustering are essential.', 'IN_23_11', TO_DATE('22-09-2022', 'DD-MM-YYYY'), 'Q3_ML_20_A_STU_22_1')
INTO reply  VALUES ('R17', 'Feature scaling, regularization, and cross-validation are techniques to prevent overfitting in ML models.', 'IN_23_12', TO_DATE('23-09-2022', 'DD-MM-YYYY'), 'Q4_ML_20_A_STU_22_1')
INTO reply VALUES ('R18', 'Advanced AI applications include natural language processing, computer vision, and autonomous robotics.', 'IN_23_16', TO_DATE('24-09-2022', 'DD-MM-YYYY'), 'Q3_AI_21_B_STU_22_2')
INTO reply VALUES ('R19', 'Deep learning techniques such as neural networks and convolutional neural networks are used in AI.', 'IN_24_16', TO_DATE('25-09-2022', 'DD-MM-YYYY'), 'Q4_AI_21_B_STU_22_2')
INTO reply VALUES ('R20', 'Reinforcement learning, unsupervised learning, and transfer learning are advanced AI concepts.', 'IN_24_17', TO_DATE('26-09-2022', 'DD-MM-YYYY'), 'Q3_AI_21_A_STU_22_3')
INTO reply VALUES ('R21', 'AI ethics, fairness, and bias are important considerations in AI development and deployment.', 'IN_24_18', TO_DATE('27-09-2022', 'DD-MM-YYYY'), 'Q4_AI_21_A_STU_22_3')
INTO reply VALUES ('R22', 'Advanced data science techniques involve deep learning, ensemble methods, and feature engineering.', 'IN_20_1', TO_DATE('28-09-2022', 'DD-MM-YYYY'), 'Q3_DS_22_B_STU_22_4')
INTO reply VALUES ('R23', 'Big data analytics, time series analysis, and dimensionality reduction are important in data science.', 'IN_21_2', TO_DATE('29-09-2022', 'DD-MM-YYYY'), 'Q4_DS_22_B_STU_22_4')
INTO reply  VALUES ('R24', 'Data visualization techniques like scatter plots, histograms, and heatmaps are used to explore data.', 'IN_21_3', TO_DATE('30-09-2022', 'DD-MM-YYYY'), 'Q3_DS_23_A_STU_22_4')
INTO reply VALUES ('R25', 'Data mining, pattern recognition, and predictive modeling are common tasks in data analysis.', 'IN_22_4', TO_DATE('01-10-2022', 'DD-MM-YYYY'), 'Q4_DS_23_A_STU_22_4')
INTO reply VALUES ('R26', 'Advanced web development topics include server-side programming, authentication, and database integration.', 'IN_23_5', TO_DATE('02-10-2022', 'DD-MM-YYYY'), 'Q7_WD_20_B_STU_23_2')
INTO reply VALUES ('R27', 'Exploratory data analysis techniques like summary statistics, data profiling, and correlation analysis are used to understand data.', 'IN_20_6', TO_DATE('03-10-2022', 'DD-MM-YYYY'), 'Q3_DS_23_A_STU_22_4_2')
INTO reply VALUES ('R28', 'Machine learning pipelines involve data preprocessing, feature engineering, model training, and evaluation.', 'IN_23_7', TO_DATE('04-10-2022', 'DD-MM-YYYY'), 'Q4_DS_23_A_STU_22_4_2')
INTO reply VALUES ('R29', 'Responsive web design frameworks like Bootstrap and Foundation help in building mobile-friendly websites.', 'IN_23_8', TO_DATE('05-10-2022', 'DD-MM-YYYY'), 'Q3_WD_20_B_STU_23_1_1')
INTO reply VALUES ('R30', 'Web development tools like Visual Studio Code, Atom, and Sublime Text are commonly used by developers.', 'IN_23_9', TO_DATE('06-10-2022', 'DD-MM-YYYY'), 'Q4_WD_20_B_STU_23_1_2')
Select * from dual;


commit;